### ISSUE TITLE
Random freezes

### ISSUE THREAD

**Issue by pmsobrado** [Freakler/CheatDeviceRemastered#4]
I don't know if it's just me, but with the plugin enabled, sometimes the game freezes randomly, especially when in missions, and when in missions, specially when a transition with a fade out/in occurs. The 70% of the freezes occur when some kind of counter is on screen (Ambulance missions for example).

Sometimes the game won't even boot, giving me an error code (I'm using a PS Vita and Adrenaline/ARK). If I reboot and try again, then the game launches. The boot error seems random.

I do have other plugins enabled, may be an incompatibility thing. I have remastered controls, camera patch live, HUD, cwcheat, and such.

**Comment by Freakler** [comment]
Same reason as your other issue. Low Memory

**Comment by pmsobrado** [comment]
Thanks!
