### ISSUE TITLE
No pedestrians or vehicles when rampages active on VCS

### ISSUE THREAD

**Issue by pmsobrado** [Freakler/CheatDeviceRemastered#5]
Right now I'm trying to complete rampages on VCS and with this plugin active it is almost impossible. No vehicles or pedestrians spawn, or very minimal, making it impossible to complete the rampages. When the plugin is not active, the game load the assets fine, there's a huge difference. I suspect some memory problem.

If I remember correctly, in LCS I did complete all the rampages without any issues with the plugin active, but if you are going to look into this problem, it would be good to check LCS as well.

**Comment by Freakler** [comment]
On real Hardware the memory is limited yes and with this plugin it is pushed to the very limit really. 

For VCS the first sign is that the game wont spawn new traffic or Pedestrians. In comparison LCS isn't as advanced and doesn't do this but ultimately just crash.

Check the Readme. If your PSP model allows it you need to enable "High Memory Layout" or try the lite version if not. 

So yes it is a known Problem. There isn't much more that can be optimized and with the latest release the advanced memory is mandatory!

**Comment by pmsobrado** [comment]
I have the "High Memory Layout" enabled. It is a PS Vita btw, but of course it's a real PSP hardware after all. Thanks for the clarification!

**Comment by pmsobrado** [comment]
@Freakler BTW, with the lite version, settings cannot be saved, I guess it is normal behaviour?

Thanks!

**Comment by Freakler** [comment]
Yes, no config for the lite version to safe on RAM. You can observe the Memory if you enable the "Display Memory Usage" under Misc

**Comment by pmsobrado** [comment]
But isn't the settings saved on a file? How does the settings save work for it to affect RAM?

Thanks!
