### ISSUE TITLE
Doesn't launch on LCS (PPSSPP)

### ISSUE THREAD

**Issue by LtFrankDrebin** [Freakler/CheatDeviceRemastered#8]
Hello, Freakler. I want to report that CheatDeviceRemastered refuses to launch when I play LCS on the latest version of PPSSPP emulator. The VCS version works perfectly, it opens when I press L + directional buttons, but nothing happens when I press those same buttons in LCS. The PPSSPP version I launch both of the games on is the same one, I just choose a different ISO in the menu, so it's hardly a PPSSPP issue. Could you please look into it?

**Comment by Freakler** [comment]
I suggest you join our Discord server for help. https://discord.gg/7DERFmkgYq
Sadly there are always problems with PPSSPP :/

**Comment by LtFrankDrebin** [comment]
Thank you for your help on Discord. I'm closing this thread as reverting to the default PPSSPP settings has fixed my issue.
