### ISSUE TITLE
can't start GTA LCS

### ISSUE THREAD

**Issue by artmih24** [Freakler/CheatDeviceRemastered#9]
can't start GTA LCS on PPSSPP, GTA LCS both US and European versions, PPSSPP ver. 1.16.6

**Comment by Freakler** [comment]
Set PSP Clock to 1000 (System -> Change emulated PSP's CPU clock (unstable))
If that doesn't help delete "cheatdevice_names_lcs.ini"

**Comment by artmih24** [comment]
Thanks!
